export default {
    NEW_TODO: 'TODO_NEW',

    LIST_REQUEST_SAGA: 'TODO_LIST_REQUEST_SAGA',
    LIST_REQUEST_SAGA_SUCCESS: 'TODO_LIST_REQUEST_SAGA_SUCCESS',
    LIST_REQUEST_SAGA_FAILURE: 'TODO_LIST_REQUEST_SAGA_FAILURE',

    SAVE_REQUEST_SAGA: 'TODO_SAVE_REQUEST_SAGA',
    SAVE_REQUEST_SAGA_SUCCESS: 'TODO_SAVE_REQUEST_SAGA_SUCCESS',
    SAVE_REQUEST_SAGA_FAILURE: 'TODO_SAVE_REQUEST_SAGA_FAILURE',

    DELETE_REQUEST_SAGA: 'TODO_DELETE_REQUEST_SAGA',
    DELETE_REQUEST_SAGA_SUCCESS: 'TODO_DELETE_REQUEST_SAGA_SUCCESS',
    DELETE_REQUEST_SAGA_FAILURE: 'TODO_DELETE_REQUEST_SAGA_FAILURE',

    LIST_REQUEST: 'TODO_LIST_REQUEST',
    SAVE_REQUEST: 'TODO_SAVE_REQUEST',
    DELETE_REQUEST: 'TODO_DELETE_REQUEST',

    FORM_ID: 'TODO_FORM'
}